 
@startuml E-learning 画面遷移図
hide circle
skinparam linetype ortho
title 全体図　E-learning
 
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~項目の編集は上の方~~矢印、関係性の編集は下の方~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



entity "ページの名前" as ページの名前 {
  役割
  --
  ページ内のコンテンツ
  ・ボタン、リンク
}
 

 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 entity "TOP" as TOP {
  ランディングページ
  --
・ログイン
・新規登録
}
 
entity "ログイン" as ログイン {
  認証
  --
  入力フォーム:ID/PASS
  ・ログインボタン
  ・新規登録アカウント作成リンク
  ・パスワード再発行リンク
}
 
entity "新規アカウント作成" as 新規登録 {
  生徒・講師アカウント作成
  --
  入力フォーム:色々
  ・新規登録ボタン
}
entity "パスワード再発行" as パスワード再発行 {
  Emailヘ再発行リンク送信
  --
  メールアドレス入力フォーム
  ・パスワード再発行ボタン
}


 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~管理者マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
entity "管理者マイページ" as 管理者マイページ {
  全アカウントのテータス確認
  --
  ・講師一覧、登録、編集、削除
  ・生徒一覧、

}
 
entity "講師一覧" as 講師一覧 {
  講師アカウントの管理
  --
  ・講師登録、編集、削除、
  ステータス確認、リンク
}
  '~~~~~~~~~~~~~~~~~管理者マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~生徒・講師共有~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 entity "動画検索" as 動画検索 {
  動画の検索、視聴履歴管理
  --
  ・検索ワード入力フォーム
  ・検索ボタン
  ・ソートボタン（新旧、評価、時間、再生数）
  ・検索結果のリスト
}
 
entity "動画視聴ページ" as 動画視聴ページ {
  動画の再生
  --
  ・再生画面（ボタン色々）
  ・テスト受験ページへのリンク
  ・前の動画へのリンク
  ・次の動画へのリンク
  ・視聴済みチェックボタン
}
 
 '~~~~~~~~~~~~~~~~~生徒・講師共有~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


 
 
 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~講師マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 
entity "講師マイページ" as 講師マイページ {
  自分と生徒のステータス確認
  --
  通知画面（予定・タスク）
  ・生徒一覧
  ・生徒日報一覧
  ・動画検索
  ・my動画一覧
  ・myテスト一覧
  ・アカウント設定（講師）

}
entity "生徒一覧" as 生徒一覧 {
  生徒プロフィールの管理
  --
  ・生徒登録、編集、削除
  ステータス確認、リンク
}
entity "生徒日報一覧" as 生徒日報一覧 {
  生徒日報の管理
  --
  ・生徒日報の確認
}
 
entity "my動画一覧" as my動画一覧 {
  登録した動画の一覧
  --
  ・新しい動画の追加
  ・動画リストの確認
}
entity "myテスト一覧" as myテスト一覧 {
  登録したテストの一覧
  --
  ・新しいテストの追加
  ・テストリストの確認
}
entity "my動画編集アップロードページ" as my動画編集アップロードページ {
  登録した動画の管理
  --
  ・ファイルアップロード
  ・タイトル内容タグ等編集
  ・ステータス確認（視聴回数、スター率）
  ・テストとの紐づけ
}
entity "テスト作成フォーム" as テスト作成フォーム {
  作成したテストの管理
  --
  ・テスト作成
  ・編集、削除、
  ・ステータス確認（受験回数、正答率）
  ・動画との紐づけ
}
 
entity "講師アカウント設定" as 講師アカウント設定 {
  アカウント設定確認
  --
  メールアドレス
  パスワード
  ・編集ボタン
}
entity "講師プロフィール設定" as 講師プロフィール設定 {
  アカウント設定編集
  --
    詳細なプロフィール色々
  ・編集ボタン
}
 
 
 '~~~~~~~~~~~~~~~~講師マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 

 
 
 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~生徒マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
entity "生徒マイページ" as 生徒マイページ {
  自分のステータス確認のみ
  --
  ・日報一覧
  ・動画検索
  ・テスト一覧
  ・行動実績確認
  ・アカウント設定

}

entity "行動実績確認" as 行動実績確認 {
  自分の行動実績の確認
  --
    ・動画視聴履歴とステータス
    ・テスト受験履歴とステータス
}
 
entity "日報一覧" as 日報一覧 {
  日報の管理
  --
  ・日報のリスト（確認、追加、編集、削除）
}
entity "テスト一覧" as テスト一覧 {
  テストの管理
  --
  ・成績のまとめ
  ・テストのリスト（確認）
}

entity "テスト受験ページ" as テスト受験ページ {
  確認テスト
  --
  ・問題と選択肢のリスト
  ・解答送信ボタン
}
entity "生徒プロフィール設定" as 生徒プロフィール設定 {
  設定項目メニュー
  --
  ・アカウント情報
  ・資格情報
  ・就活状況
}
 
entity "日報編集ページ" as 日報編集ページ {
  日報の編集
  --
  ・各項目のリスト
  ・更新ボタン
  }
entity "生徒アカウント設定" as 生徒アカウント設定 {
  生徒アカウントの編集
  --
  ・各項目のリスト
  ・更新ボタン
}
entity "資格情報" as 資格情報 {
  資格情報の編集
  --
  ・各項目のリスト
  ・更新ボタン
}
entity "就活状況" as 就活状況 {
  就活状況の編集
  --
  ・各項目のリスト
  ・更新ボタン
}
 
 '~~~~~~~~~~~~~生徒マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

'#######################################################
'以下のコードを触ると矢印（関係性）を変更できる。
'たまにエラー出るのでこまめに保存とプレビュー推奨
'文字を選択した状態でCtrl + D で同じ文字列を複数選択可、一気に編集できる。
'#######################################################


'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~生徒・講師共有~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

動画検索-->動画視聴ページ
  動画視聴ページ-->テスト受験ページ


'~~~~~~~~~~~~~~~~~~~生徒・講師共有~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~生徒マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 
生徒マイページ-->日報一覧
  日報一覧-->日報編集ページ
生徒マイページ-->動画検索
生徒マイページ-->テスト一覧
  テスト一覧-->テスト受験ページ
 

生徒マイページ-->行動実績確認
  行動実績確認-->テスト受験ページ
    テスト受験ページ-->テスト結果確認ページ
  行動実績確認-->テスト結果確認ページ
  行動実績確認-->動画視聴ページ
 
生徒マイページ-->生徒プロフィール設定
  生徒プロフィール設定-->生徒アカウント設定
  生徒プロフィール設定-->資格情報
  生徒プロフィール設定-->就活状況

 '~~~~~~~~~~~~~生徒マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~講師マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 


講師マイページ-->生徒一覧
  生徒一覧-->生徒マイページや日報
講師マイページ-->生徒日報一覧

講師マイページ-->my動画一覧
  my動画一覧-->my動画編集アップロードページ
 

講師マイページ-->myテスト一覧
  myテスト一覧-->テスト作成フォーム
 
 
講師マイページ-->講師アカウント設定
  講師アカウント設定-->講師プロフィール設定

講師マイページ-->動画検索



'~~~~~~~~~~~~~~~~~~~講師マイページ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 
TOP-->新規登録
  新規登録-->確認画面
    確認画面-->完了画面
TOP-->ログイン
  ログイン-->パスワード再発行
    パスワード再発行-->確認画面2
      確認画面2-->完了画面2

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  ログイン-->生徒アカウント
    生徒アカウント-->生徒マイページ
  ログイン-->講師アカウント
    講師アカウント-->講師マイページ

  ログイン-->管理者アカウント
      管理者アカウント-->管理者マイページ
      管理者マイページ-->講師一覧
        講師一覧-->講師詳細ページ
      管理者マイページ-->生徒一覧
 
 
 
 


 
 
 
 
@enduml
 
 

